<?php

namespace Acme\Demo\DomainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository implements NoteRepositoryInterface
{
    /**
     * @return null|object
     */
    public function fetchLatest(){
        return $this->findOneBy(array(),array('id'=>'DESC'));
    }

}